name: vla
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - absl-py=0.12.0
  - aiohttp=3.7.4
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cachetools=4.2.2
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=3.4.7
  - cudatoolkit=11.0.221
  - dbus=1.13.18
  - decorator=5.0.6
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.3.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fsspec=2021.4.0
  - future=0.18.2
  - glib=2.68.1
  - google-auth=1.30.0
  - google-auth-oauthlib=0.4.1
  - grpcio=1.33.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.10
  - importlib-metadata=3.10.0
  - importlib_metadata=3.10.0
  - intel-openmp=2021.2.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.17.0
  - jinja2=2.11.3
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - lcms2=2.12
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - multidict=5.1.0
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - ninja=1.10.2
  - notebook=6.3.0
  - numpy=1.20.1
  - numpy-base=1.20.1
  - oauthlib=3.0.1
  - olefile=0.46
  - openssl=1.1.1k
  - packaging=20.9
  - pandoc=2.12
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.0.1
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - protobuf=3.14.0
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.8.1
  - pyjwt=2.1.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.7.1
  - pytorch-lightning=1.2.10
  - pyyaml=5.3.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=5.0.3
  - qtpy=1.9.0
  - readline=8.1
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - send2trash=1.5.0
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.35.4
  - tensorboard=2.4.1
  - tensorboard-plugin-wit=1.8.0
  - terminado=0.9.4
  - testpath=0.4.4
  - tk=8.6.10
  - torchaudio=0.7.2
  - torchmetrics=0.3.1
  - torchvision=0.8.2
  - tornado=6.1
  - tqdm=4.60.0
  - traitlets=5.0.5
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
      - appdirs==1.4.4
      - black==21.4b2
      - cycler==0.10.0
      - kiwisolver==1.3.1
      - matplotlib==3.4.1
      - mypy-extensions==0.4.3
      - pathspec==0.8.1
      - pygame==2.0.1
      - regex==2021.4.4
      - toml==0.10.2
      - typed-argument-parser==1.6.2
      - typing-inspect==0.6.0
